AbstractApplicationItem: Add null guards to handlers, drop z===undefined
Items may become null on destruction or just because they are really set
to null. The Item::z index property can never be undefined, especially
on get.

Fixes the following error:

file:///usr/lib/qml/org/kde/kirigami/AbstractApplicationItem.qml:287:
TypeError: Value is null and could not be converted to an object