Revert "Respect global toolbar style for page in layers"
This reverts commit d4f438462cd468d9170b5d8fd101604d610d17cb.

Skipping (globalToolBar.row && ...) check in the alternative code pass
causes null dereference on the next line:

file:///usr/local/kde/usr/lib/qml/org/kde/kirigami/Page.qml:139:
TypeError: Cannot read property 'globalToolBar' of null